import React, {useState} from "react"
import Head from 'next/head'
import styles from '../styles/Home.module.css'

 const Home = ({pokemons}) => {

  const [visible, setVisible] = useState(9);

  return (
    <div>
      <Head>
        <title>Pokemon Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {pokemons.results.slice(0, visible).map((pokemon, idx) => (
        <div key={idx}>
          <img className={styles.pokemonImage} src={`https://img.pokemondb.net/artwork/large/${pokemon.name}.jpg`} />
          <p>{pokemon.name}</p>
        </div>
        ))}
        <button onClick={() => setVisible(prev => prev + 9)}>Show more</button>
        <button onClick={() => {setVisible(9); window.scrollTo(0, 0)}}>Load Less</button>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch("https://pokeapi.co/api/v2/pokemon/?limit=99");
  const pokemons = await response.json();

  return {
    props: {
      pokemons
    },
  };
}

export default Home;


