import React, {useState, useContext, useEffect} from "react"
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'
import { PokemonContext } from "../context/state"
import Navbar from "../components/Navbar"


 const Home = ({pokemons}) => {

  // Get all states from PokemonContext
  const {pokemonList, setPokemonList, visible, setVisible} = useContext(PokemonContext);

  useEffect(() => {
    // After the page loads, set the context state to the pokemons that we fetched
    return setPokemonList(pokemons);
  }, [])


  return (
    <>
      <Head>
        <title>Pokemon Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <div className={styles.container} id="top">
        {/* From pokemon results array we slice from index 0 to visible state which is 9 (initially), then after clicking the show more button we add 9 to visible state, which dynamically updates how many pokemons are shown */}
        {pokemons.results.slice(0, visible).map((pokemon, idx) => (
        <Link href={`/pokemon/${idx + 1}`} key={idx}>
          <div>
            <img className={styles.pokemonImage} src={`https://img.pokemondb.net/artwork/large/${pokemon.name}.jpg`} />
            <p>{pokemon.name}</p>
          </div>
        </Link>
        ))}
        <button onClick={() => {setVisible(prev => prev + 9);}}>Show more</button>
        <button onClick={() => {setVisible(9); window.scrollTo(0, 0)}}>Load Less</button>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const response = await fetch("https://pokeapi.co/api/v2/pokemon/?limit=99");
  const pokemons = await response.json();

  return {
    props: {
      pokemons
    },
  };
}

export default Home;


